# 注意规则在满足自己需求情况下，尽量做到精简，不要过度复杂，以免影响性能。
# 机场订阅 手搓订阅规则
proxy-providers:
  Airport1:
    url: "机场订阅"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: 直连
    override:
      proxy-name:
        # pattern: 匹配一个或多个连续的Emoji字符
        # + 表示匹配前面的元素一次或多次
        - pattern: "[\\x{2600}-\\x{26FF}\\x{2700}-\\x{27BF}\\x{20E3}\\x{200D}\\x{1F1E6}-\\x{1F1FF}\\x{1F300}-\\x{1F6FF}\\x{1F900}-\\x{1FAFF}]+"
        # target: 将匹配到的Emoji替换为空字符串，从而实现移除
          target: " "
        # 统一地区 香港 命名
        - pattern: '(?i)(.*)(\bHong\s?Kong\b|\bHKG?\b|深港)(.*)'
          target: '香港 $1$3'
        # 统一地区 台湾 命名
        - pattern: '(?i)(.*)(\bTaiwan\b|\bTWN?\b)(.*)'
          target: '台湾 $1$3'
        # 统一地区 日本 命名
        - pattern: '(?i)(.*)(\bJapan\b|\bJPN?\b|沪日)(.*)'
          target: '日本 $1$3'
        # 统一地区 韩国 命名
        - pattern: '(?i)(.*)(\bKorea\b|\bKO?R\b)(.*)'
          target: '韩国 $1$3'
        # 统一地区 新加坡 命名
        - pattern: '(?i)(.*)(\bSingapore\b|\bSGP?\b|狮城)(.*)'
          target: '新加坡 $1$3'
        # 统一地区 美国 命名
        - pattern: '(?i)(.*)(\bUnited\s?States\b|\bUSA?\b|\bAmerica\b)(.*)'
          target: '美国 $1$3'
        # 统一地区 马来西亚 命名
        - pattern: '(?i)(.*)(\bMalaysia\b|\bMYS?\b)(.*)'
          target: '马来西亚 $1$3'
        # 统一地区 加拿大 命名
        - pattern: '(?i)(.*)(\bCanada\b|\bCAN?\b)(.*)'
          target: '加拿大 $1$3'
        # 统一地区 越南 命名
        - pattern: '(?i)(.*)(\bViet\s?Nam\b|\bVNM?\b)(.*)'
          target: '越南 $1$3'
        # 统一地区 印度 命名
        - pattern: '(?i)(.*)(\bIndia\b|\bIND?\b)(.*)'
          target: '印度 $1$3'
        # 统一地区 澳大利亚 命名
        - pattern: '(?i)(.*)(\bAustralia\b|\bAUS?\b)(.*)'
          target: '澳大利亚 $1$3'
        # 统一地区 德国 命名
        - pattern: '(?i)(.*)(\bGermany\b|\bDEU?\b)(.*)'
          target: '德国 $1$3'
        # 统一地区 法国 命名
        - pattern: '(?i)(.*)(\bFrance\b|\bFRA?\b)(.*)'
          target: '法国 $1$3'
        # 统一地区 荷兰 命名
        - pattern: '(?i)(.*)(\bNetherlands\b|\bNLD?\b)(.*)'
          target: '荷兰 $1$3'
        # 统一地区 土耳其 命名
        - pattern: '(?i)(.*)(\bTurkey\b|\bTU?R\b)(.*)'
          target: '土耳其 $1$3'
        # 统一地区 乌克兰 命名
        - pattern: '(?i)(.*)(\bUkraine\b|\bUKR\b|\bUA\b)(.*)'
          target: '乌克兰 $1$3'
        # 统一地区 英国 命名
        - pattern: '(?i)(.*)(\bUnited\s?Kingdom\b|\bGBR?\b)(.*)'
          target: '英国 $1$3'
        # 统一地区 泰国 命名
        - pattern: '(?i)(.*)(\bThailand\b|\bTHA?\b)(.*)'
          target: '泰国 $1$3'
        # 统一地区 俄罗斯 命名
        - pattern: '(?i)(.*)(\bRussian\b|\bRUS?\b)(.*)'
          target: '俄罗斯 $1$3'
        # 统一地区 南极洲 命名
        - pattern: '(?i)(.*)(\bAntarctica\b|\bATA\b|\bAQ\b)(.*)'
          target: '南极洲 $1$3'
        # 统一地区 埃及 命名
        - pattern: '(?i)(.*)(\bEgypt\b|\bEGY?\b)(.*)'
          target: '埃及 $1$3'
        # 统一地区 意大利 命名
        - pattern: '(?i)(.*)(\bItaly\b|\bITA?\b)(.*)'
          target: '意大利 $1$3'
        # 统一地区 印尼 命名
        - pattern: '(?i)(.*)(\bIndonesia\b|\bIDN?\b|\b印度尼西亚\b)(.*)'
          target: '印尼 $1$3'
        # 统一地区 澳门 命名
        - pattern: '(?i)(.*)(\bMacao\b|\bMAC\b|\bMO\b)(.*)'
          target: '澳门 $1$3'
        # 统一地区 尼日尼亚 命名
        - pattern: '(?i)(.*)(\bNigeria\b|\bNGA?\b)(.*)'
          target: '尼日尼亚 $1$3'
        # 统一倍率命名
        - pattern: '(?i)(\d+(?:\.\d+)?)(?:倍|倍率|X)'
          target: '$1x'
        

# 节点信息
proxies:
  - {name: 直连, type: direct}

# 全局配置 
# http(s) 代理端口
port: 7890 
# socks4/4a/5 代理端口
socks-port: 7891 
# 混合端口 同时支持 HTTP(S) 和 SOCKS5 协议
mixed-port: 7892  
# redirect 透明代理端口，仅能代理 TCP 流量
redir-port: 7893 
# tproxy 透明代理端口，可代理 TCP 与 UDP 流量
tproxy-port: 7894 
# 允许其他设备经过 Clash 的代理端口访问互联网
allow-lan: true
# 绑定所有 IP 地址，允许其他设备通过这个地址访问
bind-address: "*"
# 是否允许内核接受 IPv6 流量
ipv6: false
# 统一延迟
unified-delay: true
# TCP 并发
tcp-concurrent: true
# 日志级别
log-level: warning
# 匹配进程模式
find-process-mode: 'off'
# Clash 的流量出站接口
# interface-name: en0 
# 全局客户端指纹 开启后CPU使用率会提高非常多
# global-client-fingerprint: chrome 
# TCP Keep Alive 的最大空闲时间
keep-alive-idle: 600
# TCP Keep Alive 包的间隔，单位为秒
keep-alive-interval: 15
# 禁用 TCP Keep Alive，在 Android 默认为 true
disable-keep-alive: false
# 缓存
profile: 
  # 储存 API 对策略组的选择，以供下次启动时使用
  store-selected: true 
  # 储存 fakeip 映射表，域名再次发生连接时，使用原有映射地址
  store-fake-ip: true 

# 控制面板
external-controller: 0.0.0.0:9090
secret: ""
external-ui: "/etc/mihomo/run/ui"
external-ui-name: zashboard
external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip"

# 嗅探
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - "+.baidu.com"

# 入站  
tun:
  enable: true
  # system/gvisor/mixed
  stack: mixed
  dns-hijack: [] # 劫持的dns "any:53", "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

# DNS模块
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 10.200.0.0/13  # 10.200.0.1 ~ 10.207.255.254
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:private_domain,cn_domain"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "time.*.com"
  default-nameserver:
    - 223.5.5.5
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
  # namesever尽量用运营商提供的DNS
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
 
# 出站策略
# 注意锚点必须放在引用的上方，可以集中把锚点全部放yaml的顶部。
pr: &pr {type: select, proxies: [默认代理, 香港最快, 台湾最快, 日本最快, 新加坡最快, 美国最快, 故障转移, 香港节点, 台湾节点, 日本节点, 新加坡节点, 美国节点, 高倍率, 直连],include-all-providers: true}
# 建立锚点 该锚点为: 筛选香港节点中 小于等于1倍率 的节点
hk_s: &hk_s {filter: "(?i)^(?!.* (1\\.[1-9]|\\d{2,}|[2-9])\\d*(\\.\\d+)?x(\\|.*)?$)(?!.*\\[(1\\.[1-9]|\\d{2,}|[2-9])\\d*(\\.\\d+)?x\\](\\|.*)?$).*香港.*"}
# 建立锚点 该锚点为: 筛选台湾节点中 小于等于1倍率 的节点
tw_s: &tw_s {filter: "(?i)^(?!.* (1\\.[1-9]|\\d{2,}|[2-9])\\d*(\\.\\d+)?x(\\|.*)?$)(?!.*\\[(1\\.[1-9]|\\d{2,}|[2-9])\\d*(\\.\\d+)?x\\](\\|.*)?$).*台湾.*"}
# 建立锚点 该锚点为: 筛选日本节点中 小于等于1倍率 的节点
jp_s: &jp_s {filter: "(?i)^(?!.* (1\\.[1-9]|\\d{2,}|[2-9])\\d*(\\.\\d+)?x(\\|.*)?$)(?!.*\\[(1\\.[1-9]|\\d{2,}|[2-9])\\d*(\\.\\d+)?x\\](\\|.*)?$).*日本.*"}
# 建立锚点 该锚点为: 筛选新加坡节点中 小于等于1倍率 的节点
sg_s: &sg_s {filter: "(?i)^(?!.* (1\\.[1-9]|\\d{2,}|[2-9])\\d*(\\.\\d+)?x(\\|.*)?$)(?!.*\\[(1\\.[1-9]|\\d{2,}|[2-9])\\d*(\\.\\d+)?x\\](\\|.*)?$).*新加坡.*"}
# 建立锚点 该锚点为: 筛选美国节点中 小于等于1倍率 的节点
us_s: &us_s {filter: "(?i)^(?!.* (1\\.[1-9]|\\d{2,}|[2-9])\\d*(\\.\\d+)?x(\\|.*)?$)(?!.*\\[(1\\.[1-9]|\\d{2,}|[2-9])\\d*(\\.\\d+)?x\\](\\|.*)?$).*美国.*"}
# 建立锚点 该锚点为: 筛选 大于1倍率 的高倍率节点
high_rate: &high_rate {filter: ".*( (1\\.[1-9]|[2-9]|\\d{2,})\\d*(\\.\\d+)?x|\\[(1\\.[1-9]|[2-9]|\\d{2,})\\d*(\\.\\d+)?x\\])(\\|.*)?$"}
# 建立锚点 该锚点为: 排除关键关键词的节点
ef: &ef {exclude-filter: "(?i)剩余|流量|重置|距离|套餐|官网|网址|到期|direct|Traffic|Expire|Reset"}
# Emby服务,PT服务,国外AI,GitHub,TG电报,国外抖音,奈飞视频,油管视频,谷歌服务,微软服务,苹果服务,SpeedTest,巴哈姆特,游戏代理,国外媒体,全球直连,走向全球
proxy-groups:
  - {name: 默认代理, type: select, proxies: [香港最快, 台湾最快, 日本最快, 新加坡最快, 美国最快, 故障转移, 香港节点, 台湾节点, 日本节点, 新加坡节点, 美国节点, 高倍率, 直连] ,include-all-providers: true, <<: *ef}

  - {name: 香港节点, type: select, include-all: true,  <<: [*hk_s, *ef]}
  - {name: 台湾节点, type: select, include-all: true, <<: [*tw_s, *ef]}
  - {name: 日本节点, type: select, include-all: true, <<: [*jp_s, *ef]}
  - {name: 新加坡节点, type: select, include-all: true, <<: [*sg_s, *ef]}
  - {name: 美国节点, type: select, include-all: true, <<: [*us_s, *ef]}
  - {name: 高倍率, type: select, include-all: true, <<: [*high_rate, *ef]}

  - {name: Emby服务, type: select, proxies: [直连, 香港最快, 香港节点, 默认代理, 故障转移], include-all-providers: true, <<: *ef}
  - {name: PT服务, type: select, proxies: [直连, 香港最快, 香港节点, 默认代理, 故障转移], include-all-providers: true, <<: *ef}
  - {name: 国外AI, type: select, proxies: [美国最快, 默认代理, 故障转移, 香港最快, 台湾最快, 日本最快, 新加坡最快, 美国节点, 香港节点, 台湾节点, 日本节点, 新加坡节点, 高倍率, 直连],include-all-providers: true,  <<: *ef}
  - {name: GitHub, type: select, proxies: [直连, 香港最快, 默认代理, 故障转移, 香港节点],include-all-providers: true,  <<: *ef}
  - {name: TG电报, type: select, proxies: [新加坡最快, 默认代理, 故障转移, 香港最快,  美国最快, 新加坡节点, 香港节点, 美国节点, 高倍率],include-all-providers: true,  <<: *ef}
  - {name: 国外抖音, type: select, proxies: [美国最快, 默认代理, 故障转移, 日本最快, 新加坡最快, 美国节点, 日本节点, 新加坡节点, 高倍率],include-all-providers: true,  <<: *ef}
  - {name: 奈飞视频, <<: [*pr, *ef]}
  - {name: 油管视频, <<: [*pr, *ef]}
  - {name: 谷歌服务, <<: [*pr, *ef]}
  - {name: 微软服务, <<: [*pr, *ef]}
  - {name: 苹果服务, <<: [*pr, *ef]}
  - {name: SpeedTest, <<: [*pr, *ef]}
  - {name: 巴哈姆特, <<: [*pr, *ef]}
  - {name: 游戏代理, <<: [*pr, *ef]}
  - {name: 国外媒体, <<: [*pr, *ef]}
  - {name: 全球直连, type: select, proxies: [直连, 默认代理], <<: *ef}
  - {name: 走向全球, <<: [*pr, *ef]}

  
  # 这5个最快去除了高倍率节点
  - {name: 香港最快, type: url-test, include-all: true, tolerance: 20, interval: 300, <<: [*hk_s, *ef]}
  - {name: 台湾最快, type: url-test, include-all: true, tolerance: 20, interval: 300, <<: [*tw_s, *ef]}
  - {name: 新加坡最快, type: url-test, include-all: true, tolerance: 20, interval: 300, <<: [*sg_s, *ef]}
  - {name: 日本最快, type: url-test, include-all: true, tolerance: 20, interval: 300, <<: [*jp_s, *ef]}
  - {name: 美国最快, type: url-test, include-all: true, tolerance: 20, interval: 300, <<: [*us_s, *ef]}
  # 故障转移没有去除高倍率
  - {name: 故障转移, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "^((?!(直连)).)*$", <<: *ef}
  # - {name: 全部节点, type: select, include-all: true}

# 规则匹配
# 此规则部分没有做防泄露处理，因为弊严重大于利！
# 规则将按照从上到下的顺序匹配，列表顶部的规则优先级高于其底下的规则
rules:
# 局域网,自定义走直连,自定义走代理,Emby服务,PT服务,国外AI,GitHub,TG电报,国外抖音,奈飞视频,油管视频,谷歌服务,微软服务,苹果服务,SpeedTest,巴哈姆特,游戏代理,国外媒体,全球直连,走向全球
  - RULE-SET,private_domain,直连
  - RULE-SET,go_cn,全球直连
  - RULE-SET,go_global,走向全球
  - RULE-SET,emby_service,Emby服务
  - RULE-SET,pt_service,PT服务
  - RULE-SET,ai_domain,国外AI
  - RULE-SET,github_domain,GitHub
  - RULE-SET,telegram_domain,TG电报
  - RULE-SET,tiktok_domain,国外抖音
  - RULE-SET,netflix_domain,奈飞视频
  - RULE-SET,youtube_domain,油管视频
  - RULE-SET,google_domain,谷歌服务
  - RULE-SET,microsoft_domain,微软服务
  - RULE-SET,apple_domain,苹果服务
  - RULE-SET,speedtest_domain,SpeedTest
  - RULE-SET,bahamut_domain,巴哈姆特
  - RULE-SET,steamcn_domain,游戏代理
  - RULE-SET,epic_domain,游戏代理
  - RULE-SET,GlobalMedia,国外媒体

  - RULE-SET,cn_domain,全球直连
  - RULE-SET,gfw_domain,走向全球  
  - RULE-SET,geolocation-!cn,走向全球

  - RULE-SET,google_ip,谷歌服务,no-resolve
  - RULE-SET,netflix_ip,奈飞视频,no-resolve
  - RULE-SET,telegram_ip,TG电报,no-resolve
  # - RULE-SET,cn_ip,全球直连
  # 兜底应该走直连还是走代理？全球直连or走向全球
  - MATCH,全球直连

# 规则锚点
rule-anchor:
  ipcidr_mrs: &ipcidr_mrs {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain_mrs: &domain_mrs {type: http, interval: 86400, behavior: domain, format: mrs}
  classical_text: &classical_text {type: http, interval: 86400, behavior: classical, format: text}
  classical_yaml: &classical_yaml {type: http, interval: 86400, behavior: classical, format: yaml}
# 规则集
# 局域网,自定义走直连,自定义走代理,Emby服务,PT服务,国外AI,GitHub,TG电报,国外抖音,奈飞视频,油管视频,谷歌服务,微软服务,苹果服务,SpeedTest,巴哈姆特,游戏代理,国外媒体,全球直连,走向全球
rule-providers: 
  # 局域网域名
  private_domain: { <<: *domain_mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}

  # 自定义走直连
  go_cn: { <<: *classical_yaml, url: "https://raw.githubusercontent.com/imshonechen/CustomRules/main/forClash/ruleList/go_cn.yaml"}
  # 自定义走代理
  go_global: { <<: *classical_yaml, url: "https://raw.githubusercontent.com/imshonechen/CustomRules/main/forClash/ruleList/go_global.yaml"}
  
  # 自定义Emby
  emby_service: { <<: *classical_yaml, url: "https://raw.githubusercontent.com/imshonechen/CustomRules/main/forClash/ruleList/emby_service.yaml"}
  # 自定义PT
  pt_service: { <<: *classical_yaml, url: "https://raw.githubusercontent.com/imshonechen/CustomRules/main/forClash/ruleList/pt_service.yaml"}
  
  # 国外AI
  ai_domain: {  <<: *domain_mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs" }
  # github域名
  github_domain: { <<: *domain_mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}
  # 电报域名和IP
  telegram_domain: { <<: *domain_mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
  telegram_ip: { <<: *ipcidr_mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
  # tiktok域名
  tiktok_domain: { <<: *domain_mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs"}
  # 奈飞域名和IP
  netflix_domain: { <<: *domain_mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"}
  netflix_ip: { <<: *ipcidr_mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}
  # 油管域名
  youtube_domain: { <<: *domain_mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}
  # 谷歌域名和IP
  google_domain: { <<: *domain_mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
  google_ip: { <<: *ipcidr_mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  # 微软域名
  microsoft_domain: { <<: *domain_mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
  # 苹果域名
  apple_domain: { <<: *domain_mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs"}
  # speedtest域名
  speedtest_domain: { <<: *domain_mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs"}
  # 巴哈姆特域名
  bahamut_domain: { <<: *domain_mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bahamut.mrs"}
  # steamCN域名
  steamcn_domain: { <<: *domain_mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam@cn.mrs"}
  # EPIC域名
  epic_domain: { <<: *domain_mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/epicgames.mrs"}
  # 国外媒体域名 
  GlobalMedia: { <<: *classical_yaml, url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Classical_No_Resolve.yaml"}
  # 国外域名
  gfw_domain: { <<: *domain_mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs"}
  geolocation-!cn: { <<: *domain_mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  # 国内域名
  cn_domain: { <<: *domain_mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}
  #国内IP
  cn_ip: { <<: *ipcidr_mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}


