payload:
  - DOMAIN,la.lovehd.de  # iLoveHD
  - DOMAIN,u.lovehd.de  # iLoveHD
  - DOMAIN,u3.la.wmuu.de  # iLoveHD
  - DOMAIN,s1.la.wmuu.de  # iLoveHD
  - DOMAIN,u1.la.wmuu.de  # iLoveHD
  - DOMAIN,u2.la.wmuu.de  # iLoveHD
  - DOMAIN,h1.la.wmuu.de  # iLoveHD
  - DOMAIN,u2.lovehd.de  # iLoveHD
  - DOMAIN,u1.lovehd.de  # iLoveHD
  - DOMAIN,emby.900028.xyz  # 清泉
  - DOMAIN,emby302.900028.xyz  # 清泉
  - DOMAIN-SUFFIX,uhdnow.com  # UHD
  - DOMAIN,www.uhdnow.com  # UHD
  - DOMAIN,v1.uhdnow.com  # UHD
  - DOMAIN,global.uhdnow.com  # UHD
  - DOMAIN-SUFFIX,emos.lol  # emos
  - DOMAIN-SUFFIX,emos.best  # emos
  - DOMAIN-SUFFIX,emos.club  # emos @Elephant_E
  - DOMAIN,prlon.com  # emos @Panlonn
  - DOMAIN,emos.prlo.de  # emos @Panlonn 刮刮乐刮奖
  - DOMAIN,uploader.prlo.de # emos @Panlonn 上传专用
  - DOMAIN,binary.cc.cd  # emos 带图口令红包
  - DOMAIN,wiki.emos.best  # emos wiki
  - DOMAIN,medb.lat # 媒体库统计
  # - DOMAIN-SUFFIX,makima.online # FAC
  # - DOMAIN-SUFFIX,jiashule.com # FAC
  - DOMAIN-SUFFIX,313445.xyz # FAC
  - DOMAIN-SUFFIX,zox.show  # zox
  - DOMAIN-SUFFIX,3767483.xyz  # zox
  - DOMAIN-SUFFIX,nangua.de  # 南瓜
  - DOMAIN-SUFFIX,xmsl.org  # 1111
  - DOMAIN-SUFFIX,emby.moe  # 1111
  - DOMAIN-SUFFIX,xxlb.net  # 1111
  - DOMAIN-SUFFIX,niceduck.lol  # 1111
  - DOMAIN-SUFFIX,emby.wiki   # lily
  # - DOMAIN-SUFFIX,hxd.as174.de  # hxd
  # - DOMAIN-SUFFIX,cdn.as174.de  # hxd
  # - DOMAIN-SUFFIX,cf.bili.rip  # hxd
  # - DOMAIN-SUFFIX,emby.as174.de  # hxd
  - DOMAIN-SUFFIX,bili.rip  # hxd
  - DOMAIN-SUFFIX,as174.de  # hxd
  - DOMAIN-SUFFIX,nvidia.rip  # hxd

  - DOMAIN-SUFFIX,emby.oceancloud.asia  # ocean
  - DOMAIN-SUFFIX,nsfw.oceancloud.asia  # ocean
  - DOMAIN,hka-emby.aliz.work  # hka-emby
  - DOMAIN-SUFFIX,emby.nexitally.com  # others
  - DOMAIN-SUFFIX,emby.cjpc.cc
  - DOMAIN-SUFFIX,emby.flowercloud.yt
  - DOMAIN-SUFFIX,emby.maying.club
  - DOMAIN-SUFFIX,emby.mdss.cloud
  - DOMAIN-SUFFIX,emby.ytoo.li
  - DOMAIN-SUFFIX,embyserver.ga
  - DOMAIN-SUFFIX,emby.prprcloud.com
  - DOMAIN-SUFFIX,emby.nyancat.net
  - DOMAIN-SUFFIX,emby.plusmedia.site
  - DOMAIN-SUFFIX,emby-cf.plusmedia.site
  - DOMAIN-SUFFIX,emby.xeton.dev
  - DOMAIN-SUFFIX,jellyfin.xeton.dev
  - DOMAIN-SUFFIX,movie.xeton.dev
  - DOMAIN-SUFFIX,servers.xeton.dev
  - DOMAIN-SUFFIX,emby.otakudrive.life
  - DOMAIN-SUFFIX,emby2.otakudrive.life
  - DOMAIN-SUFFIX,agahk1.jmsooo.com
  - DOMAIN-SUFFIX,agasg1.jmsooo.com
  - DOMAIN-SUFFIX,agajp1.jmsooo.com
  - DOMAIN-SUFFIX,aws.jmsooo.com
  - DOMAIN-SUFFIX,ntt1.jmsooo.com
  - DOMAIN-SUFFIX,hinet.jmsooo.com
  - DOMAIN-SUFFIX,cf1.jmsooo.com
  - DOMAIN-SUFFIX,pornemby.club
  - DOMAIN-SUFFIX,emby.immtel.com
  - DOMAIN-SUFFIX,cf.odysseyplus.site
  - DOMAIN-SUFFIX,agahk.odysseyplus.site
  - DOMAIN-SUFFIX,agasg.odysseyplus.site
  - DOMAIN-SUFFIX,ru.odysseyplus.site
  - DOMAIN-SUFFIX,line.emby.men
  - DOMAIN-SUFFIX,emby.run
  - DOMAIN-SUFFIX,emby.plusmedia.site
  - DOMAIN-SUFFIX,emby-sg.plusmedia.site
  - DOMAIN-SUFFIX,emby-cf.plusmedia.site
  - DOMAIN-SUFFIX,emby.xeton.dev
  - DOMAIN-SUFFIX,jellyfin.xeton.dev
  - DOMAIN-SUFFIX,movie.xeton.dev
  - DOMAIN-SUFFIX,servers.xeton.dev
  - DOMAIN-SUFFIX,jmsooo.com  # JMS
  - DOMAIN-SUFFIX,cf.jmsooo.com  # JMS
  - DOMAIN-SUFFIX,hk.jmsooo.com  # JMS
  - DOMAIN-SUFFIX,sg.jmsooo.com  # JMS
  - DOMAIN-SUFFIX,emby.wtf
  - DOMAIN-SUFFIX,pub1back.emby.wtf
  - DOMAIN-SUFFIX,pub2back.emby.wtf
  - DOMAIN-SUFFIX,pub3back.emby.wtf
  - DOMAIN-SUFFIX,pub1.emby.wtf
  - DOMAIN-SUFFIX,pub2.emby.wtf
  - DOMAIN-SUFFIX,pub3.emby.wtf
  - DOMAIN-SUFFIX,embyclub.com
  - DOMAIN-SUFFIX,az-hk.embyclub.com
  - DOMAIN-SUFFIX,azsgp.embyclub.com
  - DOMAIN-SUFFIX,charontv.com
  - DOMAIN-SUFFIX,emby.p-p.men
  - DOMAIN-SUFFIX,emby.aiyowei.ml
  - DOMAIN-SUFFIX,poloemby.xyz
  - DOMAIN-SUFFIX,pololine.ml
  - DOMAIN-SUFFIX,gfwemby.org
  - DOMAIN-SUFFIX,loseremby.org
  - DOMAIN-SUFFIX,cc.ccemby.tk
  - DOMAIN-SUFFIX,direct.nebula-emby.com
  - DOMAIN-SUFFIX,magpie.cyou
  - DOMAIN-SUFFIX,ccemby.tk
  - DOMAIN-SUFFIX,embyplus.club
  - DOMAIN-SUFFIX,speedx.one
  - DOMAIN-SUFFIX,embymv.tk
  - DOMAIN-SUFFIX,mjjemby.org
  - DOMAIN-SUFFIX,bddup.com
  - DOMAIN-SUFFIX,emby.cl
  - DOMAIN-SUFFIX,emby.ml
  - DOMAIN-SUFFIX,nivod4.tv
  - DOMAIN-SUFFIX,newpppp.com
  - DOMAIN-SUFFIX,freetz.top
  - DOMAIN-SUFFIX,newwan.top
  - DOMAIN-SUFFIX,shuipo.lol
  - DOMAIN-SUFFIX,dicarerhome.com
  - DOMAIN-SUFFIX,emby77.cf
  - DOMAIN-SUFFIX,embyplus.org
  - DOMAIN-SUFFIX,embytv.cf
  - DOMAIN-SUFFIX,acemby.org
  - DOMAIN-SUFFIX,ju.dog
  - DOMAIN-SUFFIX,misty.ltd
  - DOMAIN-SUFFIX,ednovas.org
  - DOMAIN-SUFFIX,deja-vu.beauty
  - DOMAIN-SUFFIX,studyfun.live
  - DOMAIN-SUFFIX,charontv.com
  - DOMAIN-SUFFIX,gtlx.org
  - DOMAIN-SUFFIX,9191001.xyz
  - DOMAIN-SUFFIX,carlos.trade
  - DOMAIN-SUFFIX,agon.cf
  - DOMAIN-SUFFIX,imetyou.top
  - DOMAIN-SUFFIX,goodisp.org
  - DOMAIN-SUFFIX,emby77.org
  - DOMAIN-SUFFIX,mius.uk
  - DOMAIN-SUFFIX,emby.eu.org
  - DOMAIN-SUFFIX,wiri.tk
  - DOMAIN-SUFFIX,285286.xyz
  - DOMAIN-SUFFIX,zi0.icu
  - DOMAIN-SUFFIX,bangumi.ca
  - DOMAIN-SUFFIX,emby.kim
  - DOMAIN-SUFFIX,4545.cf
  - DOMAIN-SUFFIX,ggtt.cf
  - DOMAIN-SUFFIX,mulgore.net
  - DOMAIN-SUFFIX,happyav.eu.org
  - DOMAIN-SUFFIX,123456.al
  - DOMAIN-SUFFIX,emby.pro
  - DOMAIN-SUFFIX,xiaoyi.one
  - DOMAIN-SUFFIX,embymv.me
  - DOMAIN-SUFFIX,infinityfly.top
  - DOMAIN-SUFFIX,lucasmedia.top
  - DOMAIN-SUFFIX,nvidia.rip
  - DOMAIN-SUFFIX,emby77.org
  - DOMAIN-SUFFIX,20120714.xyz
  - DOMAIN-SUFFIX,gugumedia.link
  - DOMAIN-SUFFIX,dicarerhome.com
  - DOMAIN-SUFFIX,starcat.eu.org
  - DOMAIN-SUFFIX,catlinks.co.uk
  - DOMAIN-SUFFIX,emby.ws
  - DOMAIN-SUFFIX,ohhhh.org
  - DOMAIN-SUFFIX,9521732.xyz
  - DOMAIN-SUFFIX,misakaf.org





