# https://raw.githubusercontent.com/imshonechen/CustomRules/refs/heads/main/forClash/ruleList/go_cn.yaml
# 本来能直连的站点
# 被误判或担心被误判成为海外站点
# 需要我们自己手动添加为白名单
# 「强制直连以下站点」
#     规则类型↓
# DOMAIN: 完全匹配域名
# DOMAIN-SUFFIX: 匹配域名后缀
# DOMAIN-KEYWORD: 关键词匹配域名
# GEOIP: IP地理位置 (国家代码)
# IP-ASN: 匹配 IP 自治系统编号
# IP-CIDR: 匹配IPv4地址段
# IP-CIDR6: 匹配IPv6地址段
# SRC-IP-CIDR: 源IP段地址
# SRC-PORT: 源端口
# DST-PORT: 目标端口
# PROCESS-NAME: 源进程名
# PROCESS-PATH: 源进程路径
# IPSET: IP集
# RULE-SET: 规则集
# SCRIPT: 脚本
# MATCH: 全匹配
#     书写规范↓
# 类型,参数
#     常用↓
# - DOMAIN,
# - DOMAIN-SUFFIX,
# - DOMAIN-KEYWORD,
# - IP-CIDR,  
payload:  
  - DOMAIN-SUFFIX,chongcong.cc  
  - DOMAIN-SUFFIX,klimu.com  
  # - DOMAIN-SUFFIX,hostloc.com  
  # - DOMAIN,subcdn.cos.cat  
  # - DOMAIN,mojie.app  
  # - DOMAIN,mojie0201.xn--8stx8olrwkucjq3b.com  
  # - DOMAIN-SUFFIX,ykkk.best  
  # - DOMAIN-SUFFIX,ykkk.tech  
  # - DOMAIN-SUFFIX,gifyu.com # 触摸春天用的图床  
  # - DOMAIN-SUFFIX,linux.do # L站走直连不太稳，有时候会卡  
  # - DOMAIN,api.deeplx.org # Linux.do翻译  
  # - DOMAIN-SUFFIX,cdn.linux.do  # Linux.do  
  - DOMAIN-SUFFIX,91xjr.com # 91小键人  
  - DOMAIN-SUFFIX,smtcdns.net  # 国内很多平台用的该CDN，如腾讯视频、哔哩哔哩、抖音等  
  - DOMAIN-SUFFIX,ping0.cc  # ping0.cc  
  - DOMAIN,emos.dolby.dpdns.org  # emos  
  - DOMAIN,emos.movier.ink  # emos  
  - DOMAIN,cmcc.movier.ink  # emos  
  - DOMAIN,emos.de5.net  # emos  
  - DOMAIN,direct.emos.lol  # emos  
  - DOMAIN,emos.huohuoaa.asia  # emos  
  - DOMAIN,emos.078899.xyz  # emos  
  - DOMAIN-SUFFIX,siliconflow.cn  # 硅基流动  
  - DOMAIN,smart.uhdnow.com  # UHD  
  - DOMAIN,smart2.uhdnow.com  # UHD  
  - DOMAIN,mlc.once.im  # UHD  
  - DOMAIN,cfbest.uhdgo.com  # UHD  
  - DOMAIN-SUFFIX,zhenyunpan.com  # CloudDrive2  
  - DOMAIN,ums.sayqz.com  # TuneFreeNext  
  - DOMAIN-SUFFIX,sayqz.com  # TuneFreeNext    
  - DOMAIN,downupdate.yz.tcdnos.com  # 腾讯游戏更新
  - PROCESS-NAME,QQSpeedGLauncherPDL.exe  # QQ飞车更新
 