payload:
  - DOMAIN-SUFFIX,ygxz.in
  - DOMAIN-SUFFIX,v2ex.com  # V2EX
  - DOMAIN-SUFFIX,gitbook.io
  - DOMAIN-SUFFIX,okjc.one
  - DOMAIN,rutracker.ru  #  rutracker.ru
  - DOMAIN-SUFFIX,qbittorrent.org  # qbittorrent
  - DOMAIN-SUFFIX,hostloc.com  # HOSTLOC
  - DOMAIN-SUFFIX,linux.do # L站 走直连不太稳，有时候会卡
  - DOMAIN,api.deeplx.org # L站 翻译
  - DOMAIN-SUFFIX,haitunt.org # 海豚
  - DOMAIN-SUFFIX,mojie.app  # 魔戒
  - DOMAIN,mojie0201.xn--8stx8olrwkucjq3b.com  # 魔戒
  - DOMAIN-SUFFIX,ykkk.best  # YKK
  - DOMAIN-SUFFIX,ykkk.tech  # YKK
  - DOMAIN-SUFFIX,milkcat.io  # 奶猫  
  - DOMAIN-SUFFIX,nexitally.com  # 奶昔  
  - DOMAIN-SUFFIX,amytele.net  # 按摩院  
  - DOMAIN-SUFFIX,immtel.com  # IMM
  - DOMAIN-SUFFIX,kuromis.com  # 库洛米  
  - DOMAIN-SUFFIX,dlercloud.com  # 墙洞  
  - DOMAIN-SUFFIX,flowercloud.net  # 花云
  - DOMAIN-SUFFIX,wd-gold.com  # 西数
  - DOMAIN-SUFFIX,halo.do  # 光环
  - DOMAIN-SUFFIX,linkcube.org  # 绿叶
  - DOMAIN-SUFFIX,shadowsocks.au  # xtom
  - DOMAIN-SUFFIX,jinglongyu.com  # CTC
  - DOMAIN-SUFFIX,synn.moe  # SYN
  - DOMAIN-SUFFIX,creamdata.net  # 奶油
  - DOMAIN-SUFFIX,paoluz.plus  # 跑路云
  - DOMAIN-SUFFIX,linkeless.com  # linkeless
  - DOMAIN-SUFFIX,afun.la # 爱翻
  - DOMAIN-SUFFIX,垃圾机场.com # 薯条
  - DOMAIN-SUFFIX,bkcloud.sbs  # BKCloud
  - DOMAIN-SUFFIX,y-too.com  # 歪兔  
  - DOMAIN-SUFFIX,to-ytoo.xyz  # 歪兔  
  - DOMAIN-SUFFIX,fanrr.net # 繁荣云
  - DOMAIN-SUFFIX,ikuuu.one  #IKUUU
  - DOMAIN-SUFFIX,mesl.cloud  # MESL
  - DOMAIN-SUFFIX,tagxx.vip  # TAG
  - DOMAIN-SUFFIX,bygcloud.com  # 白月光  
  - DOMAIN-SUFFIX,mitm.it  # mitm  