payload:
  - DOMAIN,tracker.hdchina.org
  - DOMAIN,on.springsunday.net
  - DOMAIN,t.hdhome.org
  - DOMAIN,tracker.hdsky.me
  - DOMAIN,tracker.m-team.cc
  - DOMAIN,tracker.lemonhd.net
  - DOMAIN,tracker.hdarea.club
  - DOMAIN,tracker.hdtime.org
  - DOMAIN,tracker.nanyangpt.com